FROM jenkins/inbound-agent:alpine

USER root

# Instalar Node.js, npm, Docker CLI, Buildx, Git, Bash y dependencias de sistema
RUN apk add --no-cache \
    nodejs \
    npm \
    docker-cli \
    docker-cli-buildx \
    bash \
    curl \
    git

# Instalar corepack y pnpm globalmente como root
RUN npm install -g corepack pnpm && corepack enable pnpm

# Configurar directorio del agente con permisos completos
RUN mkdir -p /home/jenkins/agent && chown -R jenkins:jenkins /home/jenkins

USER jenkins
WORKDIR /home/jenkins/agent
