# INFO del proyecto
sonar.projectKey=riwi-cine-api
sonar.projectName=mineRoyal
sonar.projectVersion=1.0

# Configuración para SonarCloud
sonar.organization=riwi-cine

# Código fuente y tests
sonar.sources=src
sonar.tests=test

# Configuración de tests y cobertura (Vitest)
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
# Ruta absoluta explícita para evitar ambigüedades
  sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusiones de cobertura y análisis
sonar.coverage.exclusions=**/*.d.ts,**/node_modules/**,**/dist/**,**/*.config.ts
sonar.exclusions=**/*.d.ts,**/node_modules/**,**/dist/

# Otros ajustes útiles
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git