import { MigrationInterface, QueryRunner } from 'typeorm';

export class ConvertUserIdsToInteger1760000200000 implements MigrationInterface {
  name = 'ConvertUserIdsToInteger1760000200000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    const usersTable = await queryRunner.getTable('users');
    const userLocationsTable = await queryRunner.getTable('user_locations');
    const userIdType = usersTable?.findColumnByName('id')?.type;

    if (!usersTable || !userLocationsTable || !userIdType) {
      throw new Error('No se encontraron las tablas necesarias para convertir los IDs de usuario.');
    }
    if (userIdType === 'integer') return;
    if (userIdType !== 'uuid' || userLocationsTable.findColumnByName('user_id')?.type !== 'uuid') {
      throw new Error(`Tipo de ID de usuario no soportado: ${userIdType}.`);
    }

    for (const foreignKey of userLocationsTable.foreignKeys.filter((key) => key.columnNames.includes('user_id'))) {
      await queryRunner.dropForeignKey(userLocationsTable, foreignKey);
    }

    await queryRunner.query(`
      ALTER TABLE "users"
        ADD COLUMN "id_new" integer GENERATED BY DEFAULT AS IDENTITY;
      ALTER TABLE "user_locations"
        ADD COLUMN "user_id_new" integer;
      UPDATE "user_locations" AS location
        SET "user_id_new" = users."id_new"
        FROM "users" AS users
        WHERE location."user_id" = users."id";
      ALTER TABLE "user_locations" ALTER COLUMN "user_id_new" SET NOT NULL;
    `);

    await queryRunner.dropPrimaryKey(usersTable);
    await queryRunner.query(`
      ALTER TABLE "user_locations" DROP COLUMN "user_id";
      ALTER TABLE "users" DROP COLUMN "id";
      ALTER TABLE "users" RENAME COLUMN "id_new" TO "id";
      ALTER TABLE "user_locations" RENAME COLUMN "user_id_new" TO "user_id";
      ALTER TABLE "users" ADD CONSTRAINT "PK_users_id" PRIMARY KEY ("id");
      ALTER TABLE "user_locations"
        ADD CONSTRAINT "UQ_user_locations_user_id" UNIQUE ("user_id"),
        ADD CONSTRAINT "FK_user_locations_user_id_users_id"
          FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE;
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const usersTable = await queryRunner.getTable('users');
    const userLocationsTable = await queryRunner.getTable('user_locations');
    const userIdType = usersTable?.findColumnByName('id')?.type;

    if (!usersTable || !userLocationsTable || !userIdType) {
      throw new Error('No se encontraron las tablas necesarias para revertir los IDs de usuario.');
    }
    if (userIdType === 'uuid') return;
    if (userIdType !== 'integer' || userLocationsTable.findColumnByName('user_id')?.type !== 'integer') {
      throw new Error(`Tipo de ID de usuario no soportado al revertir: ${userIdType}.`);
    }

    await queryRunner.query(`
      ALTER TABLE "user_locations"
        DROP CONSTRAINT IF EXISTS "FK_user_locations_user_id_users_id",
        DROP CONSTRAINT IF EXISTS "UQ_user_locations_user_id";
      ALTER TABLE "users"
        ADD COLUMN "id_old" uuid DEFAULT gen_random_uuid();
      ALTER TABLE "user_locations"
        ADD COLUMN "user_id_old" uuid;
      UPDATE "user_locations" AS location
        SET "user_id_old" = users."id_old"
        FROM "users" AS users
        WHERE location."user_id" = users."id";
      ALTER TABLE "user_locations" ALTER COLUMN "user_id_old" SET NOT NULL;
    `);

    await queryRunner.dropPrimaryKey(usersTable);
    await queryRunner.query(`
      ALTER TABLE "user_locations" DROP COLUMN "user_id";
      ALTER TABLE "users" DROP COLUMN "id";
      ALTER TABLE "users" RENAME COLUMN "id_old" TO "id";
      ALTER TABLE "user_locations" RENAME COLUMN "user_id_old" TO "user_id";
      ALTER TABLE "users" ADD CONSTRAINT "PK_users_id" PRIMARY KEY ("id");
      ALTER TABLE "user_locations"
        ADD CONSTRAINT "UQ_user_locations_user_id" UNIQUE ("user_id");
    `);
  }
}
