events {}

http {

    # 1. Definición del Grupo de Servidores Backend (Upstream)
    #  define un alias para el conjunto de servidores backend. 
    # 'backend' corresponde al nombre del servicio en docker-compose.yml. 
    # '3000' es el puerto interno donde ejecuta NestJS.

    upstream backend {
        server backend:3000;
    }

    # 2. Servidor Virtual (Virtual Host)
    server {
        
        # Puerto de escucha del proxy. Es el puerto expuesto al exterior
        # del contenedor Nginx (ver mapeo de puertos en docker-compose.yml).
        
        listen 80; 

        #cuando una petición llegue con el header Host: localhost, enrútala a este bloque server (Virtual Host)
        server_name localhost;

        # Limita el tamaño máximo del cuerpo de las peticiones a 10MB
        client_max_body_size 10M;

        # 3. Enrutamiento y Proxy Inverso
        location / {
            # Proxy pass envía la petición al upstream definido asnteriormente
            proxy_pass http://backend;
        # Soporte para conexiones HTTP/1.1 y WebSockets / Keep-Alive
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_cache_bypass $http_upgrade;

        # Preservación del contexto e identidad del cliente original
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}